# Generated by Django 5.0.3 on 2024-04-17 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "automation",
            "0004_rename_linear_regression_algorithmselection_linear_regression_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="algorithmselection",
            old_name="Decision_Tree",
            new_name="decision_Tree",
        ),
    ]
