# Generated by Django 5.0.3 on 2024-04-18 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0005_rename_decision_tree_algorithmselection_decision_tree"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accuracy",
                    models.BooleanField(
                        default=False, help_text="for regression & classification"
                    ),
                ),
                ("mse", models.BooleanField(default=False, help_text="for regression")),
                (
                    "rmse",
                    models.BooleanField(default=False, help_text="for regression"),
                ),
                ("mae", models.BooleanField(default=False, help_text="for regression")),
                (
                    "confusion_matrix",
                    models.BooleanField(default=False, help_text="for classification"),
                ),
                (
                    "roc_auc",
                    models.BooleanField(default=False, help_text="for classification"),
                ),
                (
                    "precision",
                    models.BooleanField(default=False, help_text="for classification"),
                ),
                (
                    "recall",
                    models.BooleanField(default=False, help_text="for classification"),
                ),
                (
                    "f1",
                    models.BooleanField(default=False, help_text="for classification"),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.dataset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("training_time", models.FloatField(default=0.0)),
                ("training_accuracy", models.FloatField(default=0.0)),
                ("testing_accuracy", models.FloatField(default=0.0)),
                (
                    "split",
                    models.FloatField(
                        default=0.2, help_text="default 80% train - 20% test split"
                    ),
                ),
                (
                    "random_state",
                    models.IntegerField(
                        default=42, help_text="random state for splitting the data"
                    ),
                ),
                (
                    "model_path",
                    models.FileField(
                        blank=True,
                        help_text="path to save the model",
                        null=True,
                        upload_to="models/",
                    ),
                ),
                (
                    "algo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.algorithmselection",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.dataset",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.metricselection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visualizations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("plot", models.ImageField(upload_to="plots/")),
                (
                    "algo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.algorithmselection",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.dataset",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.metricselection",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.training",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
