# Generated by Django 5.0.3 on 2024-05-04 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0008_remove_algorithmselection_linear_regression_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="My_Models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(help_text="Model Name", max_length=255),
                ),
                (
                    "model_type",
                    models.CharField(help_text="Model Type", max_length=255),
                ),
                ("model_accuracy", models.FloatField(default=0.0)),
                ("model_mse", models.FloatField(default=0.0)),
                ("model_rmse", models.FloatField(default=0.0)),
                ("model_mae", models.FloatField(default=0.0)),
                (
                    "model_confusion_matrix",
                    models.TextField(help_text="Confusion Matrix"),
                ),
                ("model_roc_auc", models.FloatField(default=0.0)),
                ("model_precision", models.FloatField(default=0.0)),
                ("model_recall", models.FloatField(default=0.0)),
                ("model_f1", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.dataset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
