# Generated by Django 5.0.3 on 2024-05-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0009_my_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="my_models",
            name="model_name",
            field=models.CharField(help_text="Name of the model", max_length=255),
        ),
        migrations.AlterField(
            model_name="my_models",
            name="model_type",
            field=models.CharField(help_text="Type of the model", max_length=255),
        ),
    ]
