# Generated by Django 5.0.6 on 2024-05-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_alter_my_models_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
