# Generated by Django 5.0.6 on 2024-05-17 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_training_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='preprocessing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.preprocessing'),
        ),
    ]
